site_name: java-tron
site_url: https://tronprotocol.github.io/documentation-zh/
repo_url: https://github.com/tronprotocol/documentation-zh

nav:
    - Home: index.md
    - java-tron入门: 
        - 入门: getting_started/getting_started_with_javatron.md
    - 使用java-tron:
        - 部署: using_javatron/installing_javatron.md
        - 备份和恢复: using_javatron/backup_restore.md
        - 轻节点: using_javatron/litefullnode.md
        - 私链网络: using_javatron/private_network.md
        - 事件订阅: architecture/event.md
        - 数据库配置: architecture/database.md
        - 网络连接: using_javatron/connecting_to_tron.md
        - 节点监控: using_javatron/metrics.md
        - 节点维护工具: using_javatron/toolkit.md
    - API接口:
        - HTTP 接口: api/http.md
        - gRPC 接口: api/rpc.md
        - jsonRPC 接口: api/json-rpc.md
    - 核心协议:
        - 波场共识: mechanism-algorithm/dpos.md
        - 超级代表: mechanism-algorithm/sr.md
        - 账户模型: mechanism-algorithm/account.md
        - 资源模型: mechanism-algorithm/resource.md
        - 智能合约: contracts/contract.md
        - 系统合约: mechanism-algorithm/system-contracts.md
        - 去中心化交易所: mechanism-algorithm/dex.md
        - 账户权限管理: mechanism-algorithm/multi-signatures.md
    - java-tron开发: 
        - 开发者指南: developers/java-tron.md
        - TIPs工作流程: developers/tips.md
        - Issue工作流程: developers/issue-workflow.md
        - 治理流程: developers/governance.md
        - 配置IDE开发环境: developers/run-in-idea.md
        - 开发示例: developers/demo.md
        - 核心模块: developers/code-structure.md
    - Dapp开发:
        - 工具: contracts/tools.md
    - 客户端: 
        - wallet-cli: clients/wallet-cli.md
    - 版本发布:
        - 新版本部署手册: releases/upgrade-instruction.md
        - 一致性检验: releases/signature_verification.md
        - 历史版本:
            - releases/versions/index.md
            - v4.8.1 (Democritus): releases/versions/v4.8.1.md
            - v4.8.0.1 (Seneca): releases/versions/v4.8.0.1.md
            - v4.8.0 (Kant): releases/versions/v4.8.0.md
            - v4.7.7 (Epicurus): releases/versions/v4.7.7.md
            - v4.7.6 (Anaximander): releases/versions/v4.7.6.md
            - v4.7.5 (Cleobulus): releases/versions/v4.7.5.md
            - v4.7.4 (Bias): releases/versions/v4.7.4.md
            - v4.7.3.1 (Solon): releases/versions/v4.7.3.1.md
            - v4.7.3 (Chilon): releases/versions/v4.7.3.md
            - v4.7.2 (Periander): releases/versions/v4.7.2.md
            - v4.7.1.1 (Pittacus): releases/versions/v4.7.1.1.md
            - v4.7.1 (Sartre): releases/versions/v4.7.1.md
            - v4.7.0.1 (Aristotle): releases/versions/v4.7.0.1.md
            - v4.6.0 (Socrates): releases/versions/v4.6.0.md
            - v4.5.2 (Aurelius): releases/versions/v4.5.2.md
            - v4.5.1 (Tertullian): releases/versions/v4.5.1.md
            - v4.4.6 (David): releases/versions/v4.4.6.md
            - v4.4.5 (Cicero): releases/versions/v4.4.5.md
            - v4.4.4 (Plotinus): releases/versions/v4.4.4.md
            - v4.4.2 (Augustinus): releases/versions/v4.4.2.md
            - v4.4.0 (Rousseau): releases/versions/v4.4.0.md
            - v4.3.0 (Bacon): releases/versions/v4.3.0.md
            - v4.2.2.1 (Epictetus): releases/versions/v4.2.2.1.md
            - v4.2.2 (Lucretius): releases/versions/v4.2.2.md
            - v4.2.0 (Plato): releases/versions/v4.2.0.md
            - v4.1.3 (Thales): releases/versions/v4.1.3.md
            - v4.1.2: releases/versions/v4.1.2.md
            - v4.1.1: releases/versions/v4.1.1.md
            - v4.0.0: releases/versions/v4.0.0.md
            - Odyssey-v3.7: releases/versions/v3.7.md
            - Odyssey-v3.6.5: releases/versions/v3.6.5.md
    - 附录: 
        - 术语表: glossary.md



theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.sections  # 启用左侧导航栏的分组
    - navigation.indexes   # 历史版本等子分组的标题点击直接打开 index.md
    - navigation.footer
    - toc.integrate
    - search.highlight  # 搜索时高亮匹配内容
    - search.suggest  # 搜索时显示建议
    - content.code.annotate  # 代码块注释
    - content.tooltips  # 内容中的工具提示
  palette:
    primary: custom  # 主色调
    accent: custom  # 强调色
  font:
    text: Roboto  # 正文字体
    code: Roboto Mono  # 代码字体
 
extra_javascript:
    - javascripts/toc.js
    - javascripts/nav-toc.js
    - javascripts/mathjax-sri.js

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences

plugins:
  - search:
     separator: '[\s\u200b\-]'  
  - exclude:
      glob:
        - clients/tron-grid.md
        - contracts/trc20.md
        - contracts/tvm.md
        - developers/contribution.md
        - developers/gpg.md
        - developers/incentives.md
        - developers/resources.md
        - faq/index.md
        - introduction/index.md
        - introduction/overview.md
        - mechanism-algorithm/shielded-TRC20-contract.md
        - mechanism-algorithm/trc10.md

